### Ce notebook permet de faire une vérification de la qualité des données avant toute consolidation, visualisation ou modélisation.

In [1]:
import pandas as pd
from pathlib import Path

### 1. Chargement de données

In [2]:
# Chemin d'accès aux données brutes

RAW_DATA_DIR = Path("../..") / "data" / "raw"

# Charger les datasets

files = {
    "idmc": "data_idmc_depuis_2000.csv",
    "solutions": "data_solutions_depuis_2000.csv",
    "decisions": "decisions_asile_depuis_2000.csv",
    "demandes": "demandes_asile_depuis_2000.csv",
    "demographie": "demographie_depuis_2000.csv",
    "pays": "countries.csv"
}


dfs = {
    name: pd.read_csv(RAW_DATA_DIR / filename)
    for name, filename in files.items()
}

for name, df in dfs.items():
    print(f"{name:15} : {df.shape[0]:,} lignes × {df.shape[1]} colonnes")

idmc            : 934 lignes × 10 colonnes
solutions       : 21,258 lignes × 13 colonnes
decisions       : 113,929 lignes × 17 colonnes
demandes        : 120,597 lignes × 14 colonnes
demographie     : 116,781 lignes × 24 colonnes
pays            : 232 lignes × 16 colonnes

### 2. Vérification de la struture des fichiers

In [3]:
# Vérification de la structure

for name, df in dfs.items():
    print("\n", "=" * 70)
    print(name.upper())
    print("=" * 70)

    print("Shape :", df.shape)
    print("\nColonnes :")
    print(df.columns.tolist())

    print("\nTypes :")
    print(df.dtypes)

    print("\nAperçu :")
    display(df.head())

 ======================================================================
IDMC
======================================================================
Shape : (934, 10)

Colonnes :
['year', 'coo_id', 'coo_name', 'coo', 'coo_iso', 'coa_id', 'coa_name', 'coa', 'coa_iso', 'total']

Types :
year         int64
coo_id       int64
coo_name    object
coo         object
coo_iso     object
coa_id       int64
coa_name    object
coa         object
coa_iso     object
total        int64
dtype: object

Aperçu :

,year,coo_id,coo_name,coo,coo_iso,coa_id,coa_name,coa,coa_iso,total
0,1990,262,Unknown,UKN,UNK,262,Unknown,UKN,UNK,21300000
1,1991,262,Unknown,UKN,UNK,262,Unknown,UKN,UNK,22500000
2,1992,262,Unknown,UKN,UNK,262,Unknown,UKN,UNK,25000000
3,1993,262,Unknown,UKN,UNK,262,Unknown,UKN,UNK,27500000
4,1994,262,Unknown,UKN,UNK,262,Unknown,UKN,UNK,28000000

 ======================================================================
SOLUTIONS
======================================================================
Shape : (21258, 13)

Colonnes :
['year', 'coo_id', 'coo_name', 'coo', 'coo_iso', 'coa_id', 'coa_name', 'coa', 'coa_iso', 'returned_refugees', 'resettlement', 'naturalisation', 'returned_idps']

Types :
year                  int64
coo_id                int64
coo_name             object
coo                  object
coo_iso              object
coa_id                int64
coa_name             object
coa                  object
coa_iso              object
returned_refugees    object
resettlement         object
naturalisation       object
returned_idps        object
dtype: object

Aperçu :

,year,coo_id,coo_name,coo,coo_iso,coa_id,coa_name,coa,coa_iso,returned_refugees,resettlement,naturalisation,returned_idps
0,1959,3,Albania,ALB,ALB,33,Canada,CAN,CAN,-,17,-,-
1,1959,8,Egypt,ARE,EGY,33,Canada,CAN,CAN,-,5,-,-
2,1959,12,Austria,AUS,AUT,33,Canada,CAN,CAN,-,17,-,-
3,1959,30,Bulgaria,BUL,BGR,33,Canada,CAN,CAN,-,35,-,-
4,1959,49,Czechia,CZE,CZE,33,Canada,CAN,CAN,-,36,-,-

 ======================================================================
DECISIONS
======================================================================
Shape : (113929, 17)

Colonnes :
['year', 'coo_id', 'coo_name', 'coo', 'coo_iso', 'coa_id', 'coa_name', 'coa', 'coa_iso', 'procedure_type', 'dec_level', 'dec_pc', 'dec_recognized', 'dec_other', 'dec_rejected', 'dec_closed', 'dec_total']

Types :
year               int64
coo_id             int64
coo_name          object
coo               object
coo_iso           object
coa_id             int64
coa_name          object
coa               object
coa_iso           object
procedure_type    object
dec_level         object
dec_pc            object
dec_recognized     int64
dec_other          int64
dec_rejected       int64
dec_closed         int64
dec_total          int64
dtype: object

Aperçu :

,year,coo_id,coo_name,coo,coo_iso,coa_id,coa_name,coa,coa_iso,procedure_type,dec_level,dec_pc,dec_recognized,dec_other,dec_rejected,dec_closed,dec_total
0,2000,2,Afghanistan,AFG,AFG,11,Australia,AUL,AUS,G,AR,C,38,0,25,0,63
1,2000,3,Albania,ALB,ALB,11,Australia,AUL,AUS,G,AR,C,5,0,24,0,29
2,2000,4,Algeria,ALG,DZA,11,Australia,AUL,AUS,G,AR,C,5,0,17,0,22
3,2000,8,Egypt,ARE,EGY,11,Australia,AUL,AUS,G,AR,C,21,0,50,5,76
4,2000,10,Armenia,ARM,ARM,11,Australia,AUL,AUS,G,AR,C,0,0,5,0,5

 ======================================================================
DEMANDES
======================================================================
Shape : (120597, 14)

Colonnes :
['year', 'coo_id', 'coo_name', 'coo', 'coo_iso', 'coa_id', 'coa_name', 'coa', 'coa_iso', 'procedure_type', 'app_type', 'dec_level', 'app_pc', 'applied']

Types :
year               int64
coo_id             int64
coo_name          object
coo               object
coo_iso           object
coa_id             int64
coa_name          object
coa               object
coa_iso           object
procedure_type    object
app_type          object
dec_level         object
app_pc            object
applied            int64
dtype: object

Aperçu :

,year,coo_id,coo_name,coo,coo_iso,coa_id,coa_name,coa,coa_iso,procedure_type,app_type,dec_level,app_pc,applied
0,2006,2,Afghanistan,AFG,AFG,11,Australia,AUL,AUS,G,A,AR,C,14
1,2006,3,Albania,ALB,ALB,11,Australia,AUL,AUS,G,A,AR,C,21
2,2006,4,Algeria,ALG,DZA,11,Australia,AUL,AUS,G,A,AR,C,5
3,2006,8,Egypt,ARE,EGY,11,Australia,AUL,AUS,G,A,AR,C,38
4,2006,14,Bahrain,BAH,BHR,11,Australia,AUL,AUS,G,A,AR,C,11

 ======================================================================
DEMOGRAPHIE
======================================================================
Shape : (116781, 24)

Colonnes :
['year', 'coo_id', 'coo_name', 'coo', 'coo_iso', 'coa_id', 'coa_name', 'coa', 'coa_iso', 'f_0_4', 'f_5_11', 'f_12_17', 'f_18_59', 'f_60', 'f_other', 'f_total', 'm_0_4', 'm_5_11', 'm_12_17', 'm_18_59', 'm_60', 'm_other', 'm_total', 'total']

Types :
year         int64
coo_id       int64
coo_name    object
coo         object
coo_iso     object
coa_id       int64
coa_name    object
coa         object
coa_iso     object
f_0_4        int64
f_5_11       int64
f_12_17      int64
f_18_59      int64
f_60         int64
f_other      int64
f_total      int64
m_0_4        int64
m_5_11       int64
m_12_17      int64
m_18_59      int64
m_60         int64
m_other      int64
m_total      int64
total        int64
dtype: object

Aperçu :

,year,coo_id,coo_name,coo,coo_iso,coa_id,coa_name,coa,coa_iso,f_0_4,...,f_other,f_total,m_0_4,m_5_11,m_12_17,m_18_59,m_60,m_other,m_total,total
0,2001,2,Afghanistan,AFG,AFG,2,Afghanistan,AFG,AFG,0,...,0,0,0,0,0,0,0,0,0,1226092
1,2001,91,Iran (Islamic Rep. of),IRN,IRN,2,Afghanistan,AFG,AFG,0,...,0,0,0,0,0,5,0,0,5,5
2,2001,92,Iraq,IRQ,IRQ,2,Afghanistan,AFG,AFG,0,...,0,5,0,0,0,0,0,0,0,5
3,2001,92,Iraq,IRQ,IRQ,3,Albania,ALB,ALB,0,...,0,0,0,0,0,7,0,0,7,7
4,2001,120,North Macedonia,MCD,MKD,3,Albania,ALB,ALB,0,...,0,14,0,0,0,21,0,0,21,35

 ======================================================================
PAYS
======================================================================
Shape : (232, 16)

Colonnes :
['0', 'id', 'code', 'iso', 'iso2', 'name', 'nameOrigin', 'nameLong', 'nameShort', 'nameFormal', 'nationality', 'majorArea', 'region', 'nameFr', 'majorAreaFr', 'regionFr']

Types :
0               int64
id              int64
code           object
iso            object
iso2           object
name           object
nameOrigin     object
nameLong       object
nameShort      object
nameFormal     object
nationality    object
majorArea      object
region         object
nameFr         object
majorAreaFr    object
regionFr       object
dtype: object

Aperçu :

,0,id,code,iso,iso2,name,nameOrigin,nameLong,nameShort,nameFormal,nationality,majorArea,region,nameFr,majorAreaFr,regionFr
0,1,2,AFG,AFG,AF,Afghanistan,Afghanistan,Afghanistan,Afghanistan,the Islamic State of Afghanistan,Afghan,Asia,Southern Asia,Afghanistan,Asie,Sud de l'Asie centrale
1,1,3,ALB,ALB,AL,Albania,Albania,Albania,Albania,the Republic of Albania,Albanian,Europe,Southern Europe,Albanie,Europe,Europe australe
2,1,4,ALG,DZA,DZ,Algeria,Algeria,Algeria,Algeria,the People's Democratic Republic of Algeria,Algerian,Africa,Northern Africa,Alg,Afrique,Afrique septentrionale
3,1,5,AND,AND,AD,Andorra,Andorra,Andorra,Andorra,the Principality of Andorra,Andorran,Europe,Southern Europe,Andorre,Europe,Europe australe
4,1,6,ANG,AGO,AO,Angola,Angola,Angola,Angola,the Republic of Angola,Angolan,Africa,Middle Africa,Angola,Afrique,Afrique australe

### 3. Complétude
Pour chaque colonne, on calcul le nombre et le pourcentage de valeurs manquantes.

In [4]:
def audit_missing(df):
    audit = pd.DataFrame({
        "nb_lignes": len(df),
        "nb_manquants": df.isna().sum(),
        "taux_manquants_pct": df.isna().mean() * 100
    })

    return audit.sort_values(
        "taux_manquants_pct",
        ascending=False
    )

for name, df in dfs.items():
    print(f"\n### {name.upper()}")
    display(audit_missing(df))

### IDMC

          nb_lignes  nb_manquants  taux_manquants_pct
year            934             0                 0.0
coo_id          934             0                 0.0
coo_name        934             0                 0.0
coo             934             0                 0.0
coo_iso         934             0                 0.0
coa_id          934             0                 0.0
coa_name        934             0                 0.0
coa             934             0                 0.0
coa_iso         934             0                 0.0
total           934             0                 0.0

### SOLUTIONS

                   nb_lignes  nb_manquants  taux_manquants_pct
year                   21258             0                 0.0
coo_id                 21258             0                 0.0
coo_name               21258             0                 0.0
coo                    21258             0                 0.0
coo_iso                21258             0                 0.0
coa_id                 21258             0                 0.0
coa_name               21258             0                 0.0
coa                    21258             0                 0.0
coa_iso                21258             0                 0.0
returned_refugees      21258             0                 0.0
resettlement           21258             0                 0.0
naturalisation         21258             0                 0.0
returned_idps          21258             0                 0.0

### DECISIONS

                nb_lignes  nb_manquants  taux_manquants_pct
dec_level          113929          2139            1.877485
year               113929             0            0.000000
procedure_type     113929             0            0.000000
dec_closed         113929             0            0.000000
dec_rejected       113929             0            0.000000
dec_other          113929             0            0.000000
dec_recognized     113929             0            0.000000
dec_pc             113929             0            0.000000
coa_iso            113929             0            0.000000
coo_id             113929             0            0.000000
coa                113929             0            0.000000
coa_name           113929             0            0.000000
coa_id             113929             0            0.000000
coo_iso            113929             0            0.000000
coo                113929             0            0.000000
coo_name           113929             0            0.000000
dec_total          113929             0            0.000000

### DEMANDES

                nb_lignes  nb_manquants  taux_manquants_pct
dec_level          120597          2180            1.807673
app_type           120597           358            0.296856
year               120597             0            0.000000
coo_id             120597             0            0.000000
coo_name           120597             0            0.000000
coo                120597             0            0.000000
coo_iso            120597             0            0.000000
coa_id             120597             0            0.000000
coa_name           120597             0            0.000000
coa                120597             0            0.000000
coa_iso            120597             0            0.000000
procedure_type     120597             0            0.000000
app_pc             120597             0            0.000000
applied            120597             0            0.000000

### DEMOGRAPHIE

          nb_lignes  nb_manquants  taux_manquants_pct
year         116781             0                 0.0
coo_id       116781             0                 0.0
m_total      116781             0                 0.0
m_other      116781             0                 0.0
m_60         116781             0                 0.0
m_18_59      116781             0                 0.0
m_12_17      116781             0                 0.0
m_5_11       116781             0                 0.0
m_0_4        116781             0                 0.0
f_total      116781             0                 0.0
f_other      116781             0                 0.0
f_60         116781             0                 0.0
f_18_59      116781             0                 0.0
f_12_17      116781             0                 0.0
f_5_11       116781             0                 0.0
f_0_4        116781             0                 0.0
coa_iso      116781             0                 0.0
coa          116781             0                 0.0
coa_name     116781             0                 0.0
coa_id       116781             0                 0.0
coo_iso      116781             0                 0.0
coo          116781             0                 0.0
coo_name     116781             0                 0.0
total        116781             0                 0.0

### PAYS

             nb_lignes  nb_manquants  taux_manquants_pct
nationality        232            39           16.810345
nameFormal         232            32           13.793103
nameLong           232            17            7.327586
majorAreaFr        232            17            7.327586
regionFr           232            17            7.327586
nameFr             232            14            6.034483
iso2               232             8            3.448276
majorArea          232             5            2.155172
region             232             5            2.155172
nameOrigin         232             4            1.724138
iso                232             3            1.293103
nameShort          232             3            1.293103
0                  232             0            0.000000
id                 232             0            0.000000
code               232             0            0.000000
name               232             0            0.000000